
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import dao.connectionProvider;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException

;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Sujay Nithish
 */
public class BillPage extends javax.swing.JFrame {

    /**
     * Creates new form BillPage
     */
    public DefaultTableModel cartModel;

    public BillPage() {
        initComponents();
        setLocationRelativeTo(null);
        // Initialize the cart model
        cartModel = new DefaultTableModel();
        cartModel.addColumn("Item Name");
        cartModel.addColumn("Quantity");
        cartModel.addColumn("Price");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_itemName = new javax.swing.JPanel();
        txt_ItemName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_NoOfItems = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_mrp = new javax.swing.JTextField();
        txt_total_price = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_currentDate = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        AddToCart_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_itemName.setBackground(new java.awt.Color(204, 204, 255));

        txt_ItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ItemNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Item Name :");

        jLabel2.setText("No of Items :");

        txt_NoOfItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NoOfItemsActionPerformed(evt);
            }
        });

        jLabel3.setText("MRP : ");

        txt_mrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mrpActionPerformed(evt);
            }
        });

        txt_total_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_total_priceActionPerformed(evt);
            }
        });

        jLabel4.setText("Total Price :");

        javax.swing.GroupLayout txt_itemNameLayout = new javax.swing.GroupLayout(txt_itemName);
        txt_itemName.setLayout(txt_itemNameLayout);
        txt_itemNameLayout.setHorizontalGroup(
            txt_itemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_itemNameLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addGroup(txt_itemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(txt_itemNameLayout.createSequentialGroup()
                        .addGroup(txt_itemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(txt_itemNameLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_mrp, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(txt_itemNameLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_total_price, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(201, 201, 201))
                    .addGroup(txt_itemNameLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207))
                    .addGroup(txt_itemNameLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_NoOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))))
        );

        txt_itemNameLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_ItemName, txt_NoOfItems, txt_mrp, txt_total_price});

        txt_itemNameLayout.setVerticalGroup(
            txt_itemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txt_itemNameLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(txt_itemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(txt_itemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_NoOfItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(txt_itemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_mrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(txt_itemNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_total_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTextField6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField6.setText("SSVMR BILL Section");

        jButton2.setText("Confirm");
        jButton2.setName("CONFIRM"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        AddToCart_btn.setText("Add to Cart");
        AddToCart_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToCart_btnActionPerformed(evt);
            }
        });

        reset_btn.setText("reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(241, 241, 241)
                        .addComponent(txt_currentDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reset_btn)
                                .addGap(38, 38, 38)
                                .addComponent(AddToCart_btn)
                                .addGap(40, 40, 40)
                                .addComponent(jButton1)
                                .addGap(45, 45, 45)
                                .addComponent(jButton2))
                            .addComponent(txt_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_currentDate)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_itemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(AddToCart_btn)
                    .addComponent(reset_btn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Document document = new Document();

    try {
        PdfWriter.getInstance(document, new FileOutputStream("invoice.pdf"));

        document.open();

        // Add invoice title
        Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
        Paragraph title = new Paragraph("Invoice", titleFont);
        title.setAlignment(Paragraph.ALIGN_CENTER);
        document.add(title);

        // Add current date
        Font dateFont = FontFactory.getFont(FontFactory.HELVETICA, 12);
        Paragraph date = new Paragraph("Date: " + txt_currentDate.getText(), dateFont);
        date.setAlignment(Paragraph.ALIGN_RIGHT);
        document.add(date);

        // Create table for item details
        PdfPTable table = new PdfPTable(3); // 3 columns
        table.setWidthPercentage(100);

        // Add table headers
        Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
        table.addCell(new Paragraph("Item Name", headerFont));
        table.addCell(new Paragraph("Quantity", headerFont));
        table.addCell(new Paragraph("Price (₹)", headerFont));

        // Iterate through each row in the cart model and add items to the table
        for (int i = 0; i < cartModel.getRowCount(); i++) {
            String itemName = cartModel.getValueAt(i, 0).toString();
            String quantity = cartModel.getValueAt(i, 1).toString();
            String price = cartModel.getValueAt(i, 2).toString();

            table.addCell(new Paragraph(itemName));
            table.addCell(new Paragraph(quantity));
            table.addCell(new Paragraph(price));
        }

        // Add table to the document
        document.add(table);

        // Add total amount
        double totalAmount = 0;
        for (int i = 0; i < cartModel.getRowCount(); i++) {
            totalAmount += Double.parseDouble(cartModel.getValueAt(i, 2).toString());
        }
        Paragraph total = new Paragraph("Total: ₹" + String.format("%.2f", totalAmount), headerFont);
        total.setAlignment(Paragraph.ALIGN_RIGHT);
        document.add(total);

        System.out.println("Invoice generated successfully.");
    } catch (DocumentException | IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error generating PDF: " + e.getMessage());
    } finally {
        if (document != null) {
            document.close();
        }
    }

    // Optionally, you can clear the cart model after generating the invoice
    cartModel.setRowCount(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_ItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ItemNameActionPerformed

    private void txt_NoOfItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NoOfItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NoOfItemsActionPerformed

    private void txt_mrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mrpActionPerformed

    private void txt_total_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_total_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_total_priceActionPerformed


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat myf = new SimpleDateFormat("dd-MM-yyyy");
        Calendar cal = Calendar.getInstance();
        txt_currentDate.setText(myf.format(cal.getTime()));
        String name = txt_ItemName.getText();
        String no_of_items = txt_NoOfItems.getText();
        Double price;
        try {
            Connection con = connectionProvider.getCon();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select *from products where name='" + name + "'");
            while (rs.next()) {
                txt_mrp.setText(rs.getString("mrp"));
                txt_total_price.setText(String.valueOf(Double.parseDouble(no_of_items) * Double.parseDouble(rs.getString("mrp"))));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = connectionProvider.getCon();
            Statement stmt = con.createStatement();
            String query = "TRUNCATE TABLE cart";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null, "Cart table truncated successfully.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error truncating cart table: " + e.getMessage());
        }

        setVisible(false);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void AddToCart_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToCart_btnActionPerformed
        // TODO add your handling code here:
        String itemName = txt_ItemName.getText();
        int quantity = Integer.parseInt(txt_NoOfItems.getText());
        double mrp = Double.parseDouble(txt_mrp.getText());
        double total = Double.parseDouble(txt_total_price.getText());

        // Add the item to the cart model
        cartModel.addRow(new Object[]{itemName, quantity, total});

        // Insert the data into the database
        try {
            Connection con = connectionProvider.getCon();
            PreparedStatement pst = con.prepareStatement("INSERT INTO cart (item_name, no_of_items, mrp, total) VALUES (?, ?, ?, ?)");
            pst.setString(1, itemName);
            pst.setInt(2, quantity);
            pst.setDouble(3, mrp);
            pst.setDouble(4, total);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Item added to cart and database successfully.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_AddToCart_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
        // TODO add your handling code here:

        // Clear input fields after adding to cart
        txt_ItemName.setText("");
        txt_NoOfItems.setText("");
        txt_mrp.setText("");
        txt_total_price.setText("");
    }//GEN-LAST:event_reset_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddToCart_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton reset_btn;
    private javax.swing.JTextField txt_ItemName;
    private javax.swing.JTextField txt_NoOfItems;
    private javax.swing.JLabel txt_currentDate;
    private javax.swing.JPanel txt_itemName;
    private javax.swing.JTextField txt_mrp;
    private javax.swing.JTextField txt_total_price;
    // End of variables declaration//GEN-END:variables
}
