
import java.text.SimpleDateFormat;
import java.util.Calendar;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sujay Nithish
 */
public class StartPage extends javax.swing.JFrame {

    /**
     * Creates new form StartPage
     */
    public StartPage() {
        initComponents();
    }
    public StartPage(String role) {
        initComponents();
        System.out.println(role);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void date(){
        SimpleDateFormat myf = new SimpleDateFormat("dd-MM-yyyy");
        Calendar  cal = Calendar.getInstance();
        txt_currentDate.setText(myf.format(cal.getTime()));        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShopTitle = new javax.swing.JLabel();
        btn_GetProducts = new javax.swing.JButton();
        btn_Bill = new javax.swing.JButton();
        btn_Investment = new javax.swing.JButton();
        btn_Expiry = new javax.swing.JButton();
        txt_currentDate = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StartPage");
        setMinimumSize(new java.awt.Dimension(722, 458));

        ShopTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ShopTitle.setText("BUSINESS INSIGHT NAVIGATOR");
        ShopTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_GetProducts.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_GetProducts.setText("GET PRODUCTS");
        btn_GetProducts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_GetProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GetProductsActionPerformed(evt);
            }
        });

        btn_Bill.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_Bill.setText("BILL");
        btn_Bill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BillActionPerformed(evt);
            }
        });

        btn_Investment.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_Investment.setText("PROFIT");
        btn_Investment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Investment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InvestmentActionPerformed(evt);
            }
        });

        btn_Expiry.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_Expiry.setText("EXPIRY REMAINDER");
        btn_Expiry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Expiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExpiryActionPerformed(evt);
            }
        });

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit.png"))); // NOI18N
        btn_close.setText("LOG OUT");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(ShopTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btn_GetProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btn_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btn_Investment, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(btn_Expiry, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_close)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(ShopTitle)
                .addGap(57, 57, 57)
                .addComponent(btn_GetProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Investment, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Expiry, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BillActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BillPage().setVisible(true);
            }
        });
    }//GEN-LAST:event_btn_BillActionPerformed

    private void btn_GetProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GetProductsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new InventoryProductPage().setVisible(true);
    }//GEN-LAST:event_btn_GetProductsActionPerformed

    private void btn_ExpiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExpiryActionPerformed
        // TODO add your handling code here:
        new ExpiryRemainder().setVisible(true);
    }//GEN-LAST:event_btn_ExpiryActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_InvestmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InvestmentActionPerformed
        // TODO add your handling code here:
        new ProfitPage().setVisible(true);
    }//GEN-LAST:event_btn_InvestmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ShopTitle;
    private javax.swing.JButton btn_Bill;
    private javax.swing.JButton btn_Expiry;
    private javax.swing.JButton btn_GetProducts;
    private javax.swing.JButton btn_Investment;
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel txt_currentDate;
    // End of variables declaration//GEN-END:variables
}
